# This is a basic workflow to help you get started with Actions

name: 'CFT'
on:
  workflow_dispatch:
    inputs:
     
      choice:
        type: choice
        description: Action
        options: 
        - CreateStack
        - DeleteStack
      environment:
        type: choice
        description: Environment
        options: 
        - devl
        - qual
        - cert
        - prod
      region:
        description: The region to deploy ECR to
        required: true
        default: us-west-2

jobs:
  CreateStack:
    if: ${{ inputs.choice == 'CreateStack' }}
    name: 'CFT'
    runs-on: self-hosted
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
      
    - name: 'Create/Update Stack: ECRStack'
      uses: aws-actions/aws-cloudformation-github-deploy@v1  
      with:
       name: ECRStack
       template: resource.yml
       parameter-overrides: env_params/${{inputs.environment}}.yml
       region: ${{inputs.region}}
#     - run: aws cloudformation create-stack --stack-name CFT --template-body file:resource.yml --parameters ${{inputs.environment}}.yml
#     - run: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1   
      timeout-minutes: 15
       
  DeleteStack:
    if: ${{ inputs.choice == 'DeleteStack' }}
    name: DeleteStack
    runs-on: self-hosted
    steps: 
    - name: Code Checkout
      uses: actions/checkout@v3
      
    - name: 'Delete Stack: ECRStack'
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
       template: resource.yaml
    - run: AmazonWebServices.aws-vsts-tools.CloudFormationDeleteStack.CloudFormationDeleteStack@1
    outputs:
          regionName: 'us-west-2'
          stackName: ECRStack



